import Link from "next/link"
import { requireAdminPage } from "@/lib/auth"
import prisma from "@/lib/prisma"
import AdminActionButton from "@/app/admin/components/AdminActionButton"

export default async function UsersAdminPage() {
  await requireAdminPage()
  const users = await prisma.user.findMany({ select: { id: true, name: true, email: true, role: true, blacklisted: true }, orderBy: { createdAt: "desc" }, take: 200 })

  return <div className="min-h-screen bg-[#FAF8F5] pb-16 font-sans-ui text-[#2E2A27]"><header className="sticky top-0 z-50 border-b border-[#EAE6E1] bg-white px-4 py-4 sm:px-6"><div className="container mx-auto flex items-center justify-between"><Link href="/admin" className="font-serif-display text-lg font-bold text-[#2C1B14]">KopiKarawang Admin</Link><Link href="/admin" className="text-xs text-[#6E6864] hover:text-[#2C1B14]">Kembali ke dashboard</Link></div></header><main className="container mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><h1 className="font-serif-display text-3xl font-bold text-[#2C1B14]">Kelola pengguna</h1><p className="mt-2 text-sm text-[#6E6864]">Blacklist akun yang abuse rating atau spam review.</p>{users.length === 0 ? <div className="mt-8 rounded-2xl border border-[#EAE6E1] bg-white p-10 text-center custom-shadow"><h2 className="font-serif-display text-lg font-bold text-[#2C1B14]">Belum ada pengguna</h2></div> : <div className="mt-8 overflow-hidden rounded-2xl border border-[#EAE6E1] bg-white custom-shadow"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="border-b border-[#EAE6E1] bg-[#FAF8F5]"><tr><th className="p-4">Nama</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y divide-[#EAE6E1]">{users.map((user) => <tr key={user.id}><td className="p-4 font-semibold text-[#2C1B14]">{user.name || "-"}</td><td className="p-4">{user.email}</td><td className="p-4">{user.role}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${user.blacklisted ? "bg-red-100 text-red-800" : "bg-green-100 text-green-800"}`}>{user.blacklisted ? "BLACKLIST" : "AKTIF"}</span></td><td className="p-4"><AdminActionButton method="PATCH" endpoint={`/api/admin/users/${user.id}`} label={user.blacklisted ? "Remove blacklist" : "Blacklist"} confirmMessage={user.blacklisted ? "Aktifkan user ini?" : "Blacklist user ini?"} /></td></tr>)}</tbody></table></div></div>}</main></div>
}