ALTER TABLE "Cafe"
  ADD COLUMN IF NOT EXISTS "googlePlaceId" TEXT,
  ADD COLUMN IF NOT EXISTS "googleMapsUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;

CREATE UNIQUE INDEX IF NOT EXISTS "Cafe_googlePlaceId_key"
  ON "Cafe"("googlePlaceId");